language: python
python:
  - "2.7"
install:
  - "pip install -r requirements/base.txt"
  - "pip install -r requirements/extra.txt"
  - "python setup.py develop"
script:
  - "py.test"
services:
  - couchdb
notifications:
  email: false
